Update README.md
edgexfoundry/device-virtual pull request #40
Opened 2018-10-16 03:56 UTC by andresrinivasan

Add quick build instructions.

2018-12-18 01:09 UTC, jpwhitemn commented
@andresrinivasan @cloudxxx8 - is this PR still relevant and can we approve and merge it?

2018-12-18 02:14 UTC, andresrinivasan commented
I hope those couple of lines of instructions will save someone else the time to figure it out. Remember when we could just use `ant`?

2018-12-18 03:30 UTC, jpwhitemn commented
Andre - you are missing DCO

2018-12-18 04:21 UTC, andresrinivasan commented
Corrected

2018-12-18 04:41 UTC, cloudxxx8 commented
recheck

2018-12-18 04:43 UTC, cloudxxx8 commented
DCO still failed

2018-12-18 04:44 UTC, cloudxxx8 requested changes

2018-12-18 04:44 UTC, cloudxxx8 commented on README.md
> +`java -jar target/device-virtual-0.5.0-SNAPSHOT.jar`
the latest version number is 0.7.0

2019-02-05 21:20 UTC, MightyNerdEric commented
Closing PR; project is being archived.

2019-02-05 21:20 UTC, closed without merging